WebApplication6/WebApplication6/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using WebApplication6;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    
    public class FeedbacksController : Controller
    {
        private SELABEntities db = new SELABEntities();

        // GET: Feedbacks
        
        public ActionResult Index()
        {
            var feedbacks = db.Feedbacks.Include(f => f.AspNetUser);
            return View(feedbacks.ToList());
        }
        
        public ActionResult IndexUser()
        {
            var feedbacks = db.Feedbacks.Include(f => f.AspNetUser);
            return View(feedbacks.ToList());
        }

        // GET: Feedbacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // GET: Feedbacks/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.FK_ID = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Feedbacks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Email,Message,FK_ID")] FeedBackViewModel feedback)
        {
            SELABEntities db = new SELABEntities();
            Feedback fb = new Feedback();
            if (ModelState.IsValid)
            {
                fb.Name = feedback.Name;
                fb.Email = feedback.Email;
                fb.Message = feedback.Message;
                fb.FK_ID = User.Identity.GetUserId();

                db.Feedbacks.Add(fb);
                db.SaveChanges();
                return RedirectToAction("Index", "Home"); ;
            }

            ViewBag.FK_ID = new SelectList(db.AspNetUsers, "Id", "Email", fb.FK_ID);
            return View(feedback);
        }

        // GET: Feedbacks/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_ID = new SelectList(db.AspNetUsers, "Id", "Email", feedback.FK_ID);
            feedback.FK_ID = User.Identity.GetUserId();
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Email,Message,FK_ID")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                feedback.FK_ID = User.Identity.GetUserId();
                db.Entry(feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.FK_ID = new SelectList(db.AspNetUsers, "Id", "Email", feedback.FK_ID);
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            db.Feedbacks.Remove(feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication6/WebApplication6/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
@using Microsoft.AspNet.Identity

<head>
    <meta charset="utf-8">
    <!--<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">-->
    <title></title>
    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">

    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>


</head>
<body id="page-top" class="index" style="background-color:black; font-display:block; font-style:italic">
    <div class="section">
        <!-- Navigation
        ==========================================-->
        <nav id="menu" class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-left">
                        <li id="Home" style="color:darkgoldenrod">
                            @Html.ActionLink("Visit Site Here", "Index", "Home")
                        </li>
                        <li id="Donors">
                            @Html.ActionLink("Donors", "IndexAdmin", "Donors")
                        </li>
                        <li id="Approval">
                            @Html.ActionLink("UserRequests", "IndexAdmin", "Approval")
                        </li>
                        <li id="Approval">
                            @Html.ActionLink("FeedBacks", "Index", "Feedbacks")
                        </li>
                    </ul>
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    }

                </div>
                <!-- /.navbar-collapse -->
            </div>
        </nav>
    </div>


    <div class="container body-content">
        @RenderBody()
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy;Blood Donation Management System 2018</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li>
                            <a href="#">Privacy Policy</a>
                        </li>
                        <li>
                            <a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    </div>



    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")


</body>
</html>

WebApplication6/WebApplication6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <!--<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">-->
    <title></title>
    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">

      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    

</head>
<body id="page-top" class="index" style="background-color:black; font-display:block; font-style:italic">
    <div class="section">
        <!-- Navigation
        ==========================================-->
        <nav id="menu" class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-left">
                        <li id="Home" style="color:darkgoldenrod">
                            @Html.ActionLink("Blood Donation Management System", "Index", "Home")
                        </li>
                        <li id="Donors">
                            @Html.ActionLink("Donors", "Index", "Donors")
                        </li>
                        <li id="Approval">
                            @Html.ActionLink("Post Request", "Request", "PostRequest")
                        </li>
                        <li id="Approval">
                            @Html.ActionLink("Approve Request", "Index", "Approval")
                        </li>
                        <li id="Approval">
                            @Html.ActionLink("FeedBacks", "IndexUser", "Feedbacks")
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.Partial("_LoginPartial")
                        </li>
                    </ul>

                </div>
                <!-- /.navbar-collapse -->
            </div>
        </nav>
    </div>


    <div class="container body-content">
        @RenderBody()
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy;Blood Donation Management System 2018</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li>
                            <a href="#">Privacy Policy</a>
                        </li>
                        <li>
                            <a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    </div>


    
    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

   
</body>
</html>